# Generated by Django 4.2.5 on 2023-09-17 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_message_options_message_is_from_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('SY', 'System'), ('US', 'User'), ('AS', 'Assistant')], default='US', max_length=2),
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='script',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Script'),
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='tags',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='title',
            field=models.CharField(max_length=256, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='video_id',
            field=models.CharField(max_length=20, verbose_name='Video ID'),
        ),
    ]
